# Generated by Django 5.1.4 on 2025-02-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usersubscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='detail1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='detail2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='detail3',
            field=models.TextField(default=''),
        ),
    ]
