# Generated by Django 5.1.4 on 2025-02-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_subscriptionplan_detail1_subscriptionplan_detail2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='detail1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='detail2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='detail3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
